/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (checks persistence) */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics exposition
         * @description Aggregate operational metrics for this process (HTTP edge, outbox
         *     dispatcher, run worker, Go runtime) in Prometheus text exposition
         *     format. Served only when `metrics.enabled` is true in the server
         *     configuration; otherwise the route does not exist. Labels carry
         *     fixed vocabularies only and never include tenant or resource
         *     identifiers.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a tenant */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects of the authenticated tenant */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads of the authenticated tenant */
        get: operations["listThreads"];
        put?: never;
        /** Open a thread on a project */
        post: operations["createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one thread */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages after a cursor */
        get: operations["listThreadMessages"];
        put?: never;
        /** Append a user message (the run request) */
        post: operations["appendThreadMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the runs of a thread
         * @description Runs are returned oldest first in one stable order (creation time,
         *     ties broken by ascending id) so pages never reshuffle between
         *     requests. The `after` cursor is the number of runs to skip from the
         *     start of that order; runs are never deleted, so positions are
         *     stable. A known thread without runs yields an empty `runs` array,
         *     never an error; an unknown or foreign-tenant thread yields the
         *     uniform 404 problem (no existence oracle, ADR-0004).
         */
        get: operations["listThreadRuns"];
        put?: never;
        /**
         * Start a run for the thread. Requires an `Idempotency-Key`;
         *     retrying the same call replays the same run instead of creating one.
         */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a run with its tasks */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event stream page for the run */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cooperative cancellation of an executing run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence-based run report (available once the run is terminal) */
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download artifact content
         * @description Returns raw bytes. `X-Ants-Digest` carries the SHA-256 content digest;
         *     `X-Ants-Retention` the retention class.
         */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            /** @description Stable machine-readable identifier for the failure mode */
            code: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            extras?: {
                [key: string]: unknown;
            };
        };
        TenantID: string;
        ProjectID: string;
        ThreadID: string;
        MessageID: string;
        RunID: string;
        TaskID: string;
        SpecID: string;
        ArtifactID: string;
        PrincipalID: string;
        /** @enum {string} */
        TenantStatus: "active" | "suspended" | "deleted";
        /** @enum {string} */
        PlanTier: "free" | "team" | "enterprise";
        /** Format: date-time */
        Timestamp: string;
        Tenant: {
            id: components["schemas"]["TenantID"];
            slug: string;
            name: string;
            plan: components["schemas"]["PlanTier"];
            region: string;
            status: components["schemas"]["TenantStatus"];
            /** Format: int64 */
            version: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        CreateTenantRequest: {
            slug: string;
            name: string;
            region?: string;
        };
        Project: {
            id: components["schemas"]["ProjectID"];
            tenant_id: components["schemas"]["TenantID"];
            slug: string;
            name: string;
            default_branch: string;
            /** @description Repository seed source used by the local pipeline */
            seed_name?: string;
            /** Format: int64 */
            version: number;
            created_at: components["schemas"]["Timestamp"];
        };
        CreateProjectRequest: {
            slug: string;
            name: string;
            default_branch: string;
            seed_name: string;
        };
        ProjectList: {
            projects: components["schemas"]["Project"][];
        };
        /**
         * @description Durable operational state (see master plan section 6.2)
         * @enum {string}
         */
        ThreadStatus: "idle" | "planning" | "awaiting_input" | "ready_to_execute" | "executing" | "waiting_external" | "needs_attention" | "reviewing" | "fixing" | "ready_for_review" | "merged" | "failed" | "archived";
        Thread: {
            id: components["schemas"]["ThreadID"];
            tenant_id: components["schemas"]["TenantID"];
            project_id: components["schemas"]["ProjectID"];
            title: string;
            status: components["schemas"]["ThreadStatus"];
            creator_id: components["schemas"]["PrincipalID"];
            /** Format: int64 */
            version: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ThreadList: {
            threads: components["schemas"]["Thread"][];
        };
        CreateThreadRequest: {
            project_id: components["schemas"]["ProjectID"];
            title: string;
        };
        AppendMessageRequest: {
            content: string;
        };
        Message: {
            id: components["schemas"]["MessageID"];
            tenant_id: components["schemas"]["TenantID"];
            thread_id: components["schemas"]["ThreadID"];
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            role: "user" | "agent" | "system";
            /** @enum {string} */
            delivery_mode: "immediate" | "queue" | "steer";
            content: string;
            created_at: components["schemas"]["Timestamp"];
        };
        MessagePage: {
            messages: components["schemas"]["Message"][];
            /**
             * Format: int64
             * @description Total message count for the thread
             */
            total: number;
        };
        FailureInfo: {
            code: string;
            message: string;
            transient: boolean;
        };
        /** @enum {string} */
        TaskStatus: "draft" | "queued" | "provisioning" | "working" | "verifying" | "integrating" | "done" | "waiting_external" | "blocked" | "cancelled" | "failed";
        /** @enum {string} */
        RunStatus: "pending" | "planning" | "executing_tasks" | "integrating" | "verifying" | "reporting" | "completed" | "failed" | "cancelled";
        Task: {
            id: components["schemas"]["TaskID"];
            tenant_id: components["schemas"]["TenantID"];
            run_id: components["schemas"]["RunID"];
            thread_id: components["schemas"]["ThreadID"];
            name: string;
            /** @enum {string} */
            kind: "code_change" | "integration" | "verification";
            status: components["schemas"]["TaskStatus"];
            depth: number;
            depends_on: components["schemas"]["TaskID"][];
            attempts: number;
            max_attempts: number;
            failure?: components["schemas"]["FailureInfo"];
            /** Format: int64 */
            version: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        Run: {
            id: components["schemas"]["RunID"];
            tenant_id: components["schemas"]["TenantID"];
            thread_id: components["schemas"]["ThreadID"];
            spec_id?: components["schemas"]["SpecID"];
            status: components["schemas"]["RunStatus"];
            idempotency_key: string;
            task_ids: components["schemas"]["TaskID"][];
            report?: components["schemas"]["RunReport"];
            failure?: components["schemas"]["FailureInfo"];
            /** Format: int64 */
            version: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            finished_at?: components["schemas"]["Timestamp"];
        };
        RunWithTasks: {
            run: components["schemas"]["Run"];
            tasks: components["schemas"]["Task"][];
        };
        /** @description One page of a thread's run history in stable creation order */
        RunPage: {
            runs: components["schemas"]["Run"][];
            /**
             * Format: int64
             * @description Total number of runs recorded for the thread
             */
            total: number;
        };
        Actor: {
            /** @enum {string} */
            type: "human" | "service_principal" | "system";
            id: string;
        };
        /** @description Versioned event envelope (master plan section 11.3) */
        Event: {
            id: string;
            /** @description Versioned event type; new shapes require a new .vN suffix */
            type: string;
            occurred_at: components["schemas"]["Timestamp"];
            tenant_id: components["schemas"]["TenantID"];
            aggregate_type: string;
            aggregate_id: string;
            /** Format: int64 */
            aggregate_version: number;
            actor: components["schemas"]["Actor"];
            trace_id?: string;
            /**
             * Format: int64
             * @description Monotonic pagination cursor
             */
            seq: number;
            /** @description Routing field grouping events into their run stream */
            run_id?: string;
            data: {
                [key: string]: unknown;
            };
        };
        EventPage: {
            events: components["schemas"]["Event"][];
        };
        SpecContent: {
            outcome: string;
            assumptions: string[];
            requirements: string[];
            non_goals: string[];
            success_criteria: string[];
            blockers: string[];
        };
        /** @enum {string} */
        Severity: "blocker" | "warning" | "note";
        /** @enum {string} */
        Confidence: "high" | "medium";
        Finding: {
            category: string;
            severity: components["schemas"]["Severity"];
            confidence: components["schemas"]["Confidence"];
            location: string;
            /** @description Concrete failure scenario the finding describes */
            scenario: string;
        };
        Evidence: {
            criterion: string;
            command: string[];
            exit_code: number;
            passed: boolean;
            log_artifact_id?: components["schemas"]["ArtifactID"];
            at: components["schemas"]["Timestamp"];
        };
        ReportTask: {
            id: components["schemas"]["TaskID"];
            name: string;
            branch: string;
            commit_sha?: string;
            status: components["schemas"]["TaskStatus"];
            attempts: number;
            failure?: components["schemas"]["FailureInfo"];
        };
        ReportIntegration: {
            branch: string;
            sha?: string;
            conflicts?: string[];
        };
        ReportVerification: {
            passed: boolean;
            evidence: components["schemas"]["Evidence"][];
        };
        BudgetSummary: {
            tasks_used: number;
            max_tasks: number;
            exec_ops_used: number;
            max_exec_ops: number;
        };
        ReportArtifactRef: {
            id: components["schemas"]["ArtifactID"];
            /** @enum {string} */
            kind: "diff" | "log" | "report";
            digest: string;
        };
        RunReport: {
            run_id: components["schemas"]["RunID"];
            thread_id: components["schemas"]["ThreadID"];
            spec_id: components["schemas"]["SpecID"];
            spec: components["schemas"]["SpecContent"];
            tasks: components["schemas"]["ReportTask"][];
            integration: components["schemas"]["ReportIntegration"];
            verification: components["schemas"]["ReportVerification"];
            findings: components["schemas"]["Finding"][];
            artifacts: components["schemas"]["ReportArtifactRef"][];
            budget: components["schemas"]["BudgetSummary"];
            ready_for_review: boolean;
            summary: string;
            started_at: components["schemas"]["Timestamp"];
            finished_at: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description Error as RFC 9457 Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ThreadID: components["schemas"]["ThreadID"];
        RunID: components["schemas"]["RunID"];
        TaskID: components["schemas"]["TaskID"];
        ArtifactID: components["schemas"]["ArtifactID"];
        /** @description Return entries with cursor strictly greater than this value */
        AfterCursor: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition of the current metric set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects (possibly empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    listThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Threads ordered by most recent update, bounded to a
             *     server-defined page size.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Thread created in `idle` state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listThreadMessages: {
        parameters: {
            query?: {
                /** @description Return entries with cursor strictly greater than this value */
                after?: components["parameters"]["AfterCursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages in ascending sequence order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    appendThreadMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendMessageRequest"];
            };
        };
        responses: {
            /** @description Message stored; sequence assigned by the server */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listThreadRuns: {
        parameters: {
            query?: {
                /** @description Return runs at position strictly greater than this value in the stable order */
                after?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One bounded page of the thread's runs with the total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: components["parameters"]["ThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run accepted; execution proceeds asynchronously */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunWithTasks"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                /** @description Return entries with cursor strictly greater than this value */
                after?: components["parameters"]["AfterCursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events ordered by cursor; pass the last `seq` back as `after` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getRunReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReport"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact content */
            200: {
                headers: {
                    "X-Ants-Digest"?: string;
                    "X-Ants-Retention"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/x-diff": string;
                    "application/json": string;
                    "text/plain": string;
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
